spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: CatHatMusic
  profiles:
    active: dev
  jpa:
    generate-ddl: false
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sqlMigrationPrefix: V
    sqlMigrationSeparator: __
    validateOnMigrate: true
    baselineOnMigrate: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: ${APPLICATION_PORT}
weixin:
  mp:
    app:
      id: ${MP_APP_ID}
      secret: ${MP_APP_SECRET}
cos:
  bucket: ${COS_BUCKET}
  region: ${COS_REGION}
  secret:
    id: ${COS_SECRET_ID}
    key: ${COS_SECRET_KEY}